
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  my_new_project:
    # Applies to all files under models/example/
    raw:
      +materialized: table
      +database: DBT_LABS
      +schema: RAW_SCHEMA
      +query_tag: DBT2
      +transient : false
      +pre-hook:
        - >
          INSERT INTO SNOWFLAKE_DBT_DATA.SF_SCHEMA.MODEL_RUN_AUDIT (model_name, execution_time_start)
          VALUES ('{{ model.name }}', CURRENT_TIMESTAMP);
      +post-hook:
        - >
          UPDATE SNOWFLAKE_DBT_DATA.SF_SCHEMA.MODEL_RUN_AUDIT
          SET execution_time_end = CURRENT_TIMESTAMP,
              row_count = (SELECT COUNT(*) FROM {{ this }})
          WHERE model_name = '{{ model.name }}'
            AND execution_time_end IS NULL;
    silver:
      +materialized: view
      +database: DBT_LABS_SILVER
      +schema: Silver_schema
      +query_tag: DBT_query
      append_orders:
        +materialized: incremental
        +incremental_strategy: append
      orders_merge:
        +materialized: incremental
        +incremental_strategy: merge
        +unique_key: order_id
seeds:
  my_new_project:
    +database: DBT_LABS2
    +schema: RAW_SCHEMA
    

    country_info:
      +schema: RAW_SCHEMA
      +column_types:
        country_code: varchar(100)
        country_name: varchar(100)
        region: varchar(100)
        currency: varchar(100)
        language: varchar(100)

    country_population:
      +schema: PUBLIC
      +column_types:
        country_code: varchar(15)
        population_millions: int
        gdp_usd_billions: float
    
    country_internet:
      +delimiter: '|'
      +schema: PUBLIC
      +column_types:
        country_code: varchar(100)
        internet_users_millions: number
        mobile_subscriptions_millions: number
        sim_card_prefix: varchar(10)

vars:
  name : KSR                #global variable
  database_name: SNOWFLAKE_DBT_DATA
  schema_name: SF_SCHEMA
  customer_state:
  plan_type:
  reporting_year: [2024,2023]
  reporting_month: [6,7]