
SELECT
  CAST(CUSTOMER_ID AS NUMBER(38, 0))        AS CUST_ID,
  CAST(FIRST_NAME AS VARCHAR(50))           AS FIRST_NAME,
  CAST(LAST_NAME AS VARCHAR(50))            AS LAST_NAME,
  CAST((FIRST_NAME || ' ' || LAST_NAME ) AS VARCHAR(50))    AS FULL_NAME,
  CAST(EMAIL AS VARCHAR(100))               AS EMAIL,
  CAST(PHONE AS VARCHAR(20))                AS PHN_NUMBER,
  CAST(CITY AS VARCHAR(50))                 AS CITY,
  CAST(STATE AS VARCHAR(50))                AS STATE
FROM {{ source('raw_data', 'cust') }}
