version: 2

snapshots:
  - name: supply_chain_orders_snapshot_new
    relation: source('raw_data', 'supply_chain')
    config:
      database: DBT_LABS
      schema: SILVER_SCH
      unique_key: ORDER_ID
      strategy: timestamp
      updated_at: UPDATED_AT
      hard_deletes: ignore  
      dbt_valid_to_current: "to_date('9999-12-31')" 
  - name: supply_chain_orders_snapshot_key_based_new
    description: >
      Check-based snapshot for tracking changes across key business columns.
      Ignores deletes unless explicitly configured.
    relation: source('raw_data', 'supply_chain')
    config:
      database: DBT_LABS
      schema: SILVER_SCH
      unique_key: ORDER_ID
      strategy: check
      check_cols: ['SUPPLIER_NAME','PRODUCT_NAME','QUANTITY','UNIT_COST','TOTAL_COST','STATUS','DELIVERY_DATE']
      hard_deletes: invalidate  # options are: 'ignore', 'invalidate'
      dbt_valid_to_current: "to_date('9999-12-31')" # Specifies that current records should have `dbt_valid_to` set to `'9999-12-31'` instead of `NULL`.
      query_tag: dbt